name: CI - Teste Python

on:
  push:
    branches: [ "desenvolvimento" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Rodar script
      run: python main.py

    - name: Notificar no Discord
      if: always()
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"content": "🚀 CI executado com status: ${{ job.status }}"}' \
        ${{ secrets.DISCORD_WEBHOOK }}
        
